#print('line1 line2' , sep = '')
#print (format(1236.5559) , '.2f')
#course = 'CPRG-216'
#print('welcome to programming course {}'.format(course))
#credits = 3
#print('Course Code: {}  Credits: {:.1f}'.format(course, credits))
#print('Course Code: {1}  Credits: {0:.1f}'.format(credits, course))

#name = 'ARSHDEEP'
#print ('my name is {} ' .format(name))
#SAIT_Course = 'Information technology services'
#credites = 30
#print('my name is {} my course at SAIT is {} and the credits for this are{: .2f}' .format(name, SAIT_Course, credites))
#average = 76.55523
#print(f'the average is {average : .3f}')
#amount = 55.236912336547896523412558
#print(f'the amount is {amount : .5f}')
#course = "CPNT-219"
#print(f'the course is {course: ^25}')

#yesterday = +0.7588
#Today = +0.7479
#Change = -0.0109

#print('{:>9} {:>9}' . format("Date" , "Rate") )
#print('{:>9} {:>9}' . format("=====", "====="))
#print('{:>9} {:>9}'. format ("yesterday" , yesterday))
#print('{:>9} {:>9}' . format('Today' , Today))
#print('{:>9} {:>9}' .format("change" , Change))

# printing numbers from 0 to 1000
#i = 0
#while i<=1000 :
#    print(i)
 #   i = i + 1


#for j in range (1000):
 #   print (j)
  #  j = j + 1

#grade = float(input("Please entwe a valid grade  :"))
#while grade>=0 or grade<=100 :
#    print(f'You entered {grade}. This is valid grade')
#if grade<0 or grade > 100:
#        grade = float(input("Please entwe a valid grade  :"))
 #       print('Program Ends')

#num= 1
#while num <= 10 :
  #  print(num)
  #  num = num + 2
#else:
 #   print(f'{num } is > 10')




   
#year = int(input('plaese input the year : '))

#if year % 4 == 0 and  ( year % 100 != 0 or year % 400 == 0) :
 #       print('it is a leap year')
#else:
#    print("it is not a leap year")


#KM_PER_MILE = 1.61
#print(format(" MPH", "10s"), format(" KPH", "10s"))
#print(format("==========", "10s"), format("==========", "10s"))
#for mph in range(10, 80, 10):
 #    kph = mph * KM_PER_MILE
  #   print(format(mph, "10d"), format(kph, "10.0f"))

#for i in range (10) :
 #   if i == 5 :
  #      break
   # print(i)
#print(' i am out of loop')

#for i in range (7):
 #   for j in range(5) :
  #      print(i,'*', j ,'=' , i*j )

#number_rows = int(input('Please input the number of rows : '))
#number_columns = int(input('Please input the number of columns :'))
#for rows in range (number_rows) :
 #   for columns in range (number_columns) :
  #      print('*' , end='')
#print()

#greetings = """hello! this is arshdeep khurana"""
#course = ' OOPS1'

#print(greetings + course)

#my = 'hello this is oops1'
#for che in my :
#    print(che )
#print(  len(my))

#print('go flames go'  .isdigit())

#course = input ('Enter a course code: ')
#alpha = 0
#digit = 0
#for ch in course:
 #if ch.isalpha():
  #alpha += 1
#elif ch.isdigit():
#digit += 1
#print(f'There are {alpha} alphabetic characters in {course}')
#print(f'There are {digit} numeric characters in {course}')

#today_date = '18-2-2025'
#date = str(today_date).replace("-" , "/") 
#print(today_date)
#print(date)

#print("1236547896522145896325871880" .count('5'))

#names = ("Harry","Brianna","Lucy","Harry","John")
#print(names)
#Creating empty tuple
#empty_tuple = ()
#Creating a single value tuple
#motorcycle = ("BMW",)
#print(type(motorcycle)) 
#This is not tuple, what is it?
#motorcycle = ("BMW")
#print(type(motorcycle)) 

#names = ("Harry","Brianna","Lucy","Harry","John")
#print(f'Number of values is {len(names)}')
#print(names[0],names[1],names[len(names)-1])


